### PR TITLE
Beabranch

### PR DESCRIPTION
**Pull request by LibbyKnight**

### CODE REVIEW

**Comment by AdamJahur** [comment]
So all the buttons are styled the same and the page css is still good?

**Comment by LibbyKnight** [comment]
Yes I'm going to post a screenshot so u guys can check it. Let me know!

**Comment by Nickpopadopolous** [comment]
Looks good!

**Comment by dzimmerman902** [comment]
Looks good to me, once I see a screen shot I'll be more than happy to merge

**Comment by LibbyKnight** [comment]
the screenshot has been in the chat since this morning :)

**Pull request merged**
