### PR TITLE
Review style

### PR DESCRIPTION
**Pull request by jeannieaux**
I styled the New York Times review tab. Added a background image, stars and aligned text. Had to manipulate js a little due to the appends from the API into one div. Let me know what you think.

### CODE REVIEW

**Comment by dzimmerman902** [comment]
Just to let you know, I gave them IDs so you could specifically target each individual piece. You don't need just classes to style the pieces,  that's what the IDs were for.

**Comment by jeannieaux** [comment]
I changed the code to reflect your ids. The only class I kept was '.author' because #review was being used for the div and the author's name. Unless you'd like me to change the html div name .... let me know.

**Comment by Nickpopadopolous** [comment]
Looks good to me.

**Comment by AdamJahur** [comment]
Looks good. I'm jus worried if the CSS pages will conflict each other cause we have so many

**Comment by AdamJahur** [comment]
Other that it looks good

**Comment by AdamJahur** [comment]
Also if there's a background img on the 4th panel shouldn't we have background images for the rest

**Comment by LibbyKnight** [comment]
Adam! Don't complicate things!

Just kidding just kidding :D

Jeannie can you post a screenshot so we can see how it looks before merging?

**Pull request merged**
