### PR TITLE
added calendar w disabled dates and user input limitations

### PR DESCRIPTION
**Pull request by jeannieaux**
I added the datepicker calendar and disabled past dates. The user will not be able to write any characters into the text box. It will erase immediately. No error message needed in this case. Let me know what you think.
Also, I know this is not pretty, but I had to add a script into the html page. It wouldn't work in the javascript file for some reason. I tried calling the function at the end where all the other functions were called as well, but that didn't work either.

### CODE REVIEW

**Comment by dzimmerman902** [comment]
This you test it out with the zip codes? The date output has to be a certain way for the API to pull the correct movie times.

**Comment by AdamJahur** [comment]
Yea jus make sure it works with the API and see if it work for the zip codes but other than that it looks good

**Comment by Nickpopadopolous** [comment]
What they said!

**Comment by jeannieaux** [comment]
I'll do that. We're still using OnConnect correct?

**Comment by jeannieaux** [comment]
Tested it out. Everything seems to be working just fine now. I changed the date format to the way On Connect prefers. I see times and theatres.

**Comment by dzimmerman902** [comment]
Looks good to me.

**Pull request merged**
